export const outfitsExo = [
  {
    id: 'freedom_nosorog_outfit',
    name: 'Champion of Freedom',
    faction: 'freedom',
    repair: 'E',
  },
  {
    id: 'cs_exo_outfit',
    name: 'CS-5 Exoskeleton',
    faction: 'csky',
    repair: 'E',
  },
  {
    id: 'exo_outfit',
    name: 'Exoskeleton',
    faction: 'stalker',
    repair: 'E',
  },
  {
    id: 'merc_exo_outfit',
    name: 'Mercenary Exoskeleton',
    faction: 'killer',
    repair: 'E',
  },
  {
    id: 'merc_nosorog_outfit',
    name: 'Mercenary Nosorog',
    faction: 'killer',
    repair: 'E',
  },
  {
    id: 'military_exo_outfit',
    name: 'Military Stalker Exoskeleton',
    faction: 'army',
    repair: 'E',
  },
  {
    id: 'army_nosorog_outfit',
    name: 'Military Stalker Nosorog',
    faction: 'army',
    repair: 'E',
  },
  {
    id: 'monolith_exo_outfit',
    name: 'Monolith Exoskeleton',
    faction: 'monolith',
    repair: 'E',
  },
  {
    id: 'monolith_nosorog_outfit',
    name: 'Monolith Nosorog',
    faction: 'monolith',
    repair: 'E',
  },
  {
    id: 'svoboda_exo_outfit',
    name: 'Paragon of Freedom',
    faction: 'freedom',
    repair: 'E',
  },
  {
    id: 'dolg_exo_outfit',
    name: 'PSZ-10d Exoskeleton',
    faction: 'dolg',
    repair: 'E',
  },
  {
    id: 'dolg_nosorog_outfit',
    name: 'PSZ-10d Nosorog',
    faction: 'dolg',
    repair: 'E',
  },
  {
    id: 'dolg_heavy_proto_exo_outfit',
    name: 'PSZ-9d Exoskeleton',
    faction: 'dolg',
    repair: 'E',
  },
  {
    id: 'renegade_exo_outfit',
    name: 'Renegade Exoskeleton',
    faction: 'renegade',
    repair: 'E',
  },
  {
    id: 'ecolog_exo_outfit',
    name: 'Scientific Exoskeleton',
    faction: 'ecolog',
    repair: 'E',
  },
  {
    id: 'military_proto_exo_outfit',
    name: 'Skat-9 Exoskeleton',
    faction: 'army',
    repair: 'E',
  },
  {
    id: 'bandit_exo_outfit',
    name: 'Stolen Exoskeleton',
    faction: 'bandit',
    repair: 'E',
  },
  {
    id: 'isg_exo_outfit',
    name: 'UNISG Exoskeleton',
    faction: 'isg',
    repair: 'E',
  },
  {
    id: 'isg_nosorog_outfit',
    name: 'UNISG Nosorog',
    faction: 'isg',
    repair: 'E',
  },
  {
    id: 'greh_exo_outfit',
    name: 'Vyraj Power Armor',
    faction: 'greh',
    repair: 'E',
  },
];
