export const outfitsLight = [
  {
    name: "Load-bearing 'Sunset' Tactical Suit",
    id: 'bandit_nbc_outfit',
    repair: 'L',
    faction: 'bandit',
  },
  {
    name: '"Voyager" Stalker Suit',
    id: 'travel_outfit',
    repair: 'L',
    faction: 'stalker',
  },
  {
    name: 'Tactical Stalker Suit',
    id: 'nbc_outfit',
    repair: 'L',
    faction: 'stalker',
  },
  {
    name: 'CS-2t Suit',
    id: 'cs_nbc_outfit',
    repair: 'L',
    faction: 'csky',
  },
  {
    name: 'PS5-Mt Suit',
    id: 'nbc_dolg_outfit',
    repair: 'L',
    faction: 'dolg',
  },
  {
    name: 'Keeper of Freedom',
    id: 'nbc_freedom_outfit',
    repair: 'L',
    faction: 'freedom',
  },
  {
    name: 'Tactical Monolith Suit',
    id: 'monolith_nbc_outfit',
    repair: 'L',
    faction: 'monolith',
  },
  {
    name: "Load-bearing 'Twilight' Tactical Suit",
    id: 'nbc_merc_outfit',
    repair: 'L',
    faction: 'killer',
  },
  {
    name: '"Sunrise" Stalker Suit',
    id: 'stalker_outfit',
    repair: 'L',
    faction: 'stalker',
  },
  {
    name: 'Heavy Green Overcoat',
    id: 'trenchcoat_green_outfit',
    repair: 'L',
    faction: 'st_data_export_unknown',
  },
  {
    name: '"Predator" Stalker Suit',
    id: 'stalker_predator_outfit',
    repair: 'L',
    faction: 'stalker',
  },
  {
    name: 'Fenced LC Suit',
    id: 'banditmerc_outfit',
    repair: 'L',
    faction: 'bandit',
  },
  {
    name: 'Mercenary LC-S Suit',
    id: 'merc_scout_outfit',
    repair: 'L',
    faction: 'killer',
  },
  {
    name: 'PS5-M Hunter Suit',
    id: 'dolg_red_outfit',
    repair: 'L',
    faction: 'dolg',
  },
  {
    name: '"Salamander" Stalker Suit',
    id: 'stalker_salamander_outfit',
    repair: 'L',
    faction: 'stalker',
  },
  {
    name: 'Ghillie Suit',
    id: 'ghillie_outfit',
    repair: 'L',
    faction: 'st_data_export_unknown',
  },
  {
    name: '"Autumn" Stalker Suit',
    id: 'stalker_autumn_outfit',
    repair: 'L',
    faction: 'stalker',
  },
  {
    name: 'CS-2a Body Armor',
    id: 'cs_light_outfit',
    repair: 'L',
    faction: 'csky',
  },
  {
    name: 'UNISG LC-C Suit',
    id: 'isg_lcs_camo_outfit',
    repair: 'L',
    faction: 'isg',
  },
  {
    name: 'Mercenary LC-F Suit',
    id: 'merc_fighter_outfit',
    repair: 'L',
    faction: 'killer',
  },
  {
    name: 'Mercenary STS-W Body Armor',
    id: 'merc_wolven_outfit',
    repair: 'L',
    faction: 'killer',
  },
];
