export const outfitsHeavy = [
  {
    id: 'stalker_proto_exo_outfit',
    name: '"Sunrise" Exoskeleton',
    faction: 'stalker',
    repair: 'H',
  },
  {
    id: 'cs_stalker_proto_exo_outfit',
    name: 'CS-2b Exoskeleton',
    faction: 'csky',
    repair: 'H',
  },
  {
    id: 'cs_heavy_outfit',
    name: 'CS-3b Body Armor',
    faction: 'csky',
    repair: 'H',
  },
  {
    id: 'cs_scientific_outfit_good',
    name: 'CS-4a Pathfinder',
    faction: 'csky',
    repair: 'H',
  },
  {
    id: 'military_sky_outfit',
    name: 'CS-4b Armored Suit',
    faction: 'csky',
    repair: 'H',
  },
  {
    id: 'cs_exolight_outfit',
    name: 'CS-5 Exosuit',
    faction: 'csky',
    repair: 'H',
  },
  {
    id: 'light_freedom_outfit',
    name: 'Defender of Freedom',
    faction: 'freedom',
    repair: 'H',
  },
  {
    id: 'exolight_outfit',
    name: 'Exosuit',
    faction: 'stalker',
    repair: 'H',
  },
  {
    id: 'freedom_exo_vineleaf_outfit',
    name: 'Hero of Freedom',
    faction: 'freedom',
    repair: 'H',
  },
  {
    id: 'hybrid_outfit',
    name: 'Hybrid Armored Suit',
    faction: 'st_data_export_unknown',
    repair: 'H',
  },
  {
    id: 'light_dolg_outfit',
    name: 'IBAz Universal Protection Suit',
    faction: 'dolg',
    repair: 'H',
  },
  {
    id: 'light_loner_outfit',
    name: 'Interceptor Body Armor',
    faction: 'stalker',
    repair: 'H',
  },
  {
    id: 'military_freedom_outfit',
    name: 'Liberated Skat-9 Armored Suit',
    faction: 'freedom',
    repair: 'H',
  },
  {
    id: 'bandit_exolight_outfit',
    name: 'Looted Exosuit',
    faction: 'bandit',
    repair: 'H',
  },
  {
    id: 'military_bandit_outfit',
    name: 'Looted Skat-9 Armored Suit',
    faction: 'bandit',
    repair: 'H',
  },
  {
    id: 'merc_ace_outfit',
    name: 'Mercenary ACE Scientific Suit',
    faction: 'killer',
    repair: 'H',
  },
  {
    id: 'merc_exolight_outfit',
    name: 'Mercenary Exosuit',
    faction: 'killer',
    repair: 'H',
  },
  {
    id: 'exo_merc_grass_outfit',
    name: 'Mercenary Grassland Exosuit',
    faction: 'killer',
    repair: 'H',
  },
  {
    id: 'light_merc_outfit',
    name: 'Mercenary IBAz Suit',
    faction: 'killer',
    repair: 'H',
  },
  {
    id: 'merc_combat_scientific_outfit',
    name: 'Mercenary Pathfinder',
    faction: 'killer',
    repair: 'H',
  },
  {
    id: 'military_merc_outfit',
    name: 'Mercenary Skat-9 Armored Suit',
    faction: 'killer',
    repair: 'H',
  },
  {
    id: 'merc_nighthunter_outfit',
    name: 'Mercenary STS-N Body Armor',
    faction: 'killer',
    repair: 'H',
  },
  {
    id: 'exo_merc_urban_outfit',
    name: 'Mercenary Urban Exosuit',
    faction: 'killer',
    repair: 'H',
  },
  {
    id: 'exo_merc_wood_outfit',
    name: 'Mercenary Woodland Exosuit',
    faction: 'killer',
    repair: 'H',
  },
  {
    id: 'military_exolight_outfit',
    name: 'Military Stalker Exosuit',
    faction: 'army',
    repair: 'H',
  },
  {
    id: 'light_voen_outfit',
    name: 'Military Stalker IBAz Suit',
    faction: 'army',
    repair: 'H',
  },
  {
    id: 'monolith_exolight_outfit',
    name: 'Monolith Exosuit',
    faction: 'monolith',
    repair: 'H',
  },
  {
    id: 'light_monolit_outfit',
    name: 'Monolith IBAz Assault Suit',
    faction: 'monolith',
    repair: 'H',
  },
  {
    id: 'monolith_trenchcoat_outfit',
    name: 'Monolith Overcoat',
    faction: 'monolith',
    repair: 'H',
  },
  {
    id: 'military_monolit_outfit',
    name: 'Monolith Skat-9 Armored Suit',
    faction: 'monolith',
    repair: 'H',
  },
  {
    id: 'dolg_specops_red_outfit',
    name: 'PS5-B2 Veteran Battlesuit',
    faction: 'dolg',
    repair: 'H',
  },
  {
    id: 'dolg_proto_exo_outfit',
    name: 'PS5-M Exoskeleton',
    faction: 'dolg',
    repair: 'H',
  },
  {
    id: 'dolg_exolight_outfit',
    name: 'PSZ-10d Duty Battlesuit',
    faction: 'dolg',
    repair: 'H',
  },
  {
    id: 'exo_dolg_outfit',
    name: 'PSZ-10d Duty Battlesuit',
    faction: 'dolg',
    repair: 'H',
  },
  {
    id: 'exo_dolg_red_outfit',
    name: 'PSZ-10d Venator Battlesuit',
    faction: 'dolg',
    repair: 'H',
  },
  {
    id: 'exo_dolg_urban_outfit',
    name: 'PSZ-10g Urban Battlesuit',
    faction: 'dolg',
    repair: 'H',
  },
  {
    id: 'exo_dolg_wood_outfit',
    name: 'PSZ-10l Forest Battlesuit',
    faction: 'dolg',
    repair: 'H',
  },
  {
    id: 'dolg_pantsir_outfit',
    name: 'PSZ-7p Shell Armor',
    faction: 'dolg',
    repair: 'H',
  },
  {
    id: 'dolg_heavy_outfit',
    name: 'PSZ-9d Body Armor',
    faction: 'dolg',
    repair: 'H',
  },
  {
    id: 'dolg_heavy_redline_outfit',
    name: 'PSZ-9kl Command Armor',
    faction: 'dolg',
    repair: 'H',
  },
  {
    id: 'greh_trenchcoat_outfit',
    name: 'Sin Heavy Overcoat',
    faction: 'greh',
    repair: 'H',
  },
  {
    id: 'military_outfit',
    name: 'Skat-9 Armored Suit',
    faction: 'army',
    repair: 'H',
  },
  {
    id: 'ecolog_proto_exo_outfit',
    name: 'SSP-99M Exoskeleton',
    faction: 'ecolog',
    repair: 'H',
  },
  {
    id: 'isg_exolight_outfit',
    name: 'UNISG Exosuit',
    faction: 'isg',
    repair: 'H',
  },
  {
    id: 'light_isg_outfit',
    name: 'UNISG IBAz Suit',
    faction: 'isg',
    repair: 'H',
  },
  {
    id: 'isg_proto_exo_outfit',
    name: 'UNISG Tactical Exoskeleton',
    faction: 'isg',
    repair: 'H',
  },
  {
    id: 'svoboda_exolight_outfit',
    name: 'Warrior of Freedom',
    faction: 'freedom',
    repair: 'H',
  },
  {
    id: 'svoboda_light_proto_exo_outfit',
    name: 'Wind of Freedom Exoskeleton',
    faction: 'freedom',
    repair: 'H',
  },
  {
    id: 'exo_wood_outfit',
    name: 'Woodland Exosuit',
    faction: 'st_data_export_unknown',
    repair: 'H',
  },
  {
    id: 'monolith_proto_exo_outfit',
    name: 'X-18 Exoskeleton',
    faction: 'monolith',
    repair: 'H',
  },
];
