export const outfitsField = [
  {
    name: 'Heavy Freedom Overcoat',
    id: 'trenchcoat_freedom_brown_outfit',
    repair: 'F',
    faction: 'freedom',
  },
  {
    name: 'Overcoat',
    id: 'trenchcoat_outfit',
    repair: 'F',
    faction: 'st_data_export_unknown',
  },
  {
    name: 'Black Leather Jacket',
    id: 'bandit_novice_outfit',
    repair: 'F',
    faction: 'bandit',
  },
  {
    name: "Firearm Enthusiast's Jacket",
    id: 'novice_outfit_camo',
    repair: 'F',
    faction: 'st_data_export_unknown',
  },
  {
    name: 'Tourist’s Jacket',
    id: 'novice_outfit_tourist',
    repair: 'F',
    faction: 'stalker',
  },
  {
    name: 'CS-1 Body Armor',
    id: 'cs_light_novice_outfit',
    repair: 'F',
    faction: 'csky',
  },
  {
    name: 'Clear Sky Leather Jacket',
    id: 'cs_novice_outfit',
    repair: 'F',
    faction: 'csky',
  },
  {
    name: 'Duty Leather Jacket',
    id: 'dolg_novice_outfit',
    repair: 'F',
    faction: 'dolg',
  },
  {
    name: 'Leather Jacket',
    id: 'novice_outfit',
    repair: 'F',
    faction: 'st_data_export_unknown',
  },
  {
    name: 'Freedom Leather Jacket',
    id: 'svoboda_novice_outfit',
    repair: 'F',
    faction: 'freedom',
  },
  {
    name: 'Military Service Outfit',
    id: 'army_outfit',
    repair: 'F',
    faction: 'army',
  },
  {
    name: 'Redline Leather Jacket',
    id: 'redline_novice_outfit',
    repair: 'F',
    faction: 'st_data_export_unknown',
  },
  {
    name: 'Armored Leather Jacket',
    id: 'bandit_novice_outfit_alt',
    repair: 'F',
    faction: 'bandit',
  },
];
