export const outfitsMedium = [
  {
    name: '"Bear" Stalker Suit',
    id: 'stalker_bear_outfit',
    repair: 'M',
    faction: 'stalker',
  },
  {
    name: '"Drought" Stalker Suit',
    id: 'stalker_drought_outfit',
    repair: 'M',
    faction: 'stalker',
  },
  {
    name: '"Graphite" Stalker Suit',
    id: 'stalker_graphite_outfit',
    repair: 'M',
    faction: 'stalker',
  },
  { name: '"Nomad" Stalker Suit', id: 'nomad_outfit', repair: 'M', faction: 'stalker' },
  {
    name: '"Sunset" Tactical Suit',
    id: 'bandit_sun_outfit',
    repair: 'M',
    faction: 'bandit',
  },
  {
    name: '"Tigerstripe" Stalker Suit',
    id: 'stalker_tigerstripe_outfit',
    repair: 'M',
    faction: 'stalker',
  },
  {
    name: '"Twilight" Tactical Suit',
    id: 'merc_sun_outfit',
    repair: 'M',
    faction: 'killer',
  },
  {
    name: '"Wastelander" Stalker Suit',
    id: 'wastelander_outfit',
    repair: 'M',
    faction: 'stalker',
  },
  { name: 'Berill-5M Armored Suit', id: 'specops_outfit', repair: 'M', faction: 'army' },
  { name: 'CS-2b Body Armor', id: 'cs_stalker_outfit', repair: 'M', faction: 'csky' },
  { name: 'CS-3a Body Armor', id: 'cs_medium_outfit', repair: 'M', faction: 'csky' },
  { name: 'CS-4a SEVA Suit', id: 'cs_scientific_outfit', repair: 'M', faction: 'csky' },
  {
    name: "Deserter's B-5M Armored Suit",
    id: 'specops_bandit_outfit',
    repair: 'M',
    faction: 'bandit',
  },
  {
    name: 'Fenced PS5-M Universal Protection Suit',
    id: 'bandit_ps5_outfit',
    repair: 'M',
    faction: 'bandit',
  },
  {
    name: 'Guardian of Freedom',
    id: 'svoboda_heavy_outfit',
    repair: 'M',
    faction: 'freedom',
  },
  {
    name: 'Heavy Brown Overcoat',
    id: 'trenchcoat_brown_outfit',
    repair: 'M',
    faction: 'st_data_export_unknown',
  },
  {
    name: 'Heavy Duty Overcoat',
    id: 'trenchcoat_dolg_brown_outfit',
    repair: 'M',
    faction: 'dolg',
  },
  { name: 'Irij Flak Armor', id: 'greh_armored_outfit', repair: 'M', faction: 'greh' },
  {
    name: 'ISRIT Guard Jumpsuit',
    id: 'ecolog_guard_outfit',
    repair: 'M',
    faction: 'ecolog',
  },
  {
    name: 'Looted SEVA Suit',
    id: 'bandit_scientific_outfit',
    repair: 'M',
    faction: 'bandit',
  },
  {
    name: 'Mercenary B-5M Armored Suit',
    id: 'specops_merc_outfit',
    repair: 'M',
    faction: 'killer',
  },
  { name: 'Mercenary LC Suit', id: 'merc_outfit', repair: 'M', faction: 'killer' },
  {
    name: 'Mercenary LCz Suit',
    id: 'merc_sunset_outfit',
    repair: 'M',
    faction: 'killer',
  },
  {
    name: 'Mercenary LTS-J Body Suit',
    id: 'merc_jackal_outfit',
    repair: 'M',
    faction: 'killer',
  },
  {
    name: 'Mercenary MTS-C Body Suit',
    id: 'merc_coyote_outfit',
    repair: 'M',
    faction: 'killer',
  },
  {
    name: 'Mercenary SEVA Body Armor',
    id: 'merc_scientific_armored_outfit',
    repair: 'M',
    faction: 'killer',
  },
  {
    name: 'Mercenary SEVA Suit',
    id: 'merc_scientific_outfit',
    repair: 'M',
    faction: 'killer',
  },
  {
    name: 'Monolith Patchwork Science Suit',
    id: 'monolith_scientific_light_outfit',
    repair: 'M',
    faction: 'monolith',
  },
  {
    name: 'Monolith Scientific Suit',
    id: 'monolith_scientific_outfit',
    repair: 'M',
    faction: 'monolith',
  },
  { name: 'Monolith X-18 Suit', id: 'monolith_outfit', repair: 'M', faction: 'monolith' },
  {
    name: 'Patchwork Anomaly Suit',
    id: 'bandit_scientific_dark_outfit',
    repair: 'M',
    faction: 'bandit',
  },
  {
    name: 'PS5-9Md Light Pathfinder',
    id: 'dolg_scientific_wood_outfit',
    repair: 'M',
    faction: 'dolg',
  },
  {
    name: 'PS5-9Md Light Scientific Suit',
    id: 'dolg_scientific_red_outfit',
    repair: 'M',
    faction: 'dolg',
  },
  {
    name: 'PS5-9Md Universal Scientific Suit',
    id: 'dolg_scientific_outfit',
    repair: 'M',
    faction: 'dolg',
  },
  { name: 'PS5-B Battle Armor', id: 'specops_dolg_outfit', repair: 'M', faction: 'dolg' },
  {
    name: 'PS5-M Universal Protection Suit',
    id: 'dolg_outfit',
    repair: 'M',
    faction: 'dolg',
  },
  { name: 'PS5-R Scout Vest', id: 'dolg_scout_outfit', repair: 'M', faction: 'dolg' },
  { name: 'PS6-V Warrior Suit', id: 'dolg_voin_outfit', repair: 'M', faction: 'dolg' },
  {
    name: 'Renegade LC Suit',
    id: 'renegademerc_outfit',
    repair: 'M',
    faction: 'renegade',
  },
  {
    name: 'Renegade SEVA Suit',
    id: 'renegade_scientific_outfit',
    repair: 'M',
    faction: 'renegade',
  },
  {
    name: 'Sentinel of Freedom',
    id: 'svoboda_heavy_outfit_2',
    repair: 'M',
    faction: 'freedom',
  },
  { name: 'SEVA Bodysuit', id: 'scientific_outfit', repair: 'M', faction: 'stalker' },
  { name: 'SSP-99 "Diamond"', id: 'ecolog_outfit_white', repair: 'M', faction: 'ecolog' },
  { name: 'SSP-99 Bodysuit', id: 'ecolog_outfit_orange', repair: 'M', faction: 'ecolog' },
  { name: 'SSP-99 Topaz', id: 'ecolog_outfit_yello', repair: 'M', faction: 'ecolog' },
  { name: 'SSP-99М "Ruby"', id: 'ecolog_outfit_red', repair: 'M', faction: 'ecolog' },
  {
    name: 'SSP-99M "Sapphire"',
    id: 'ecolog_outfit_blue',
    repair: 'M',
    faction: 'ecolog',
  },
  { name: 'SSP-99M Bodysuit', id: 'ecolog_outfit_green', repair: 'M', faction: 'ecolog' },
  { name: 'UNISG LC Suit', id: 'isg_lcs_outfit', repair: 'M', faction: 'isg' },
  { name: 'UNISG LC-UC Suit', id: 'isg_lcs_urban_outfit', repair: 'M', faction: 'isg' },
  {
    name: 'UNISG Mk1 Tactical Body Armor',
    id: 'isg_outfit',
    repair: 'M',
    faction: 'isg',
  },
  {
    name: 'UNISG Mk2 Tactical Body Armor',
    id: 'isg_camo_outfit',
    repair: 'M',
    faction: 'isg',
  },
  { name: 'UNISG SEVA Suit', id: 'isg_scientific_outfit', repair: 'M', faction: 'isg' },
  { name: 'Volos Flak Armor', id: 'greh_ps5_outfit', repair: 'M', faction: 'greh' },
  {
    name: 'Vyriy Flak Armor',
    id: 'greh_armored_camo_outfit',
    repair: 'M',
    faction: 'greh',
  },
  {
    name: 'Watchman of Freedom',
    id: 'svoboda_scientific_outfit',
    repair: 'M',
    faction: 'freedom',
  },
  {
    name: 'Wind of Freedom',
    id: 'svoboda_light_outfit',
    repair: 'M',
    faction: 'freedom',
  },
];
