export const shotguns = [
  {
    id: 'wpn_protecta',
    name: 'Armsel Protecta',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_protecta_nimble',
    name: 'Armsel Protecta Custom',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_ithacam37_mag',
    name: 'Ithaca M37 Defense',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_ithacam37_stakeout_20x70',
    name: 'Ithaca M37 Stakeout [20x70]',
    repair: 'B',
    ammo: 'ammo_20x70_buck',
  },
  {
    id: 'wpn_ithacam37_trench',
    name: 'Ithaca M37 Trenchgun',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_saiga12s_isg',
    name: 'KS-12',
    repair: 'D',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_ks23',
    name: 'KS-23',
    repair: 'C',
    ammo: 'ammo_23x75_shrapnel;ammo_23x75_barrikada',
  },
  {
    id: 'wpn_ks23_23_up',
    name: 'KS-23 Shortie',
    repair: 'C',
    ammo: 'ammo_23x75_shrapnel;ammo_23x75_barrikada',
  },
  {
    id: 'wpn_ks23_vorkuta',
    name: 'KS-23M "Vorkuta"',
    repair: 'C',
    ammo: 'ammo_23x75_shrapnel;ammo_23x75_barrikada',
  },
  {
    id: 'wpn_ks23_kaban',
    name: 'KS-23M Drozd',
    repair: 'C',
    ammo: 'ammo_23x75_shrapnel;ammo_23x75_barrikada',
  },
  {
    id: 'wpn_ks23_kaban_kab_up',
    name: 'KS-23M Drozd "Boar"',
    repair: 'C',
    ammo: 'ammo_23x75_shrapnel;ammo_23x75_barrikada',
  },
  {
    id: 'wpn_ksg23',
    name: 'KSG-23',
    repair: 'D',
    ammo: 'ammo_23x75_shrapnel;ammo_23x75_barrikada',
  },
  {
    id: 'wpn_benelli_m1014',
    name: 'M1014',
    repair: 'C',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_mossberg590_rail',
    name: 'Mossberg 590A1 [rail]',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_mp133',
    name: 'MP-133',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_mp153',
    name: 'MP-153',
    repair: 'C',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_mp155',
    name: 'MP-155',
    repair: 'C',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_eft_mts_255',
    name: 'MTS-255',
    repair: 'B',
    ammo: 'ammo_20x70_buck',
  },
  {
    id: 'wpn_raptr',
    name: 'RAPTR [raptr]',
    repair: 'D',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_remington870',
    name: 'Remington 870',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_saiga12s_m1',
    name: 'Saiga-12 [saiga12s_m1]',
    repair: 'C',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_saiga12s_m2',
    name: 'Saiga-12 Tactical',
    repair: 'C',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_spas12',
    name: 'SPAS-12',
    repair: 'C',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_spas12_custom',
    name: 'SPAS-12 [custom]',
    repair: 'C',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_spas12_nimble',
    name: 'SPAS-12 [nimble]',
    repair: 'C',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_toz106',
    name: 'TOZ-106',
    repair: 'A',
    ammo: 'ammo_20x70_buck',
  },
  {
    id: 'wpn_toz106_m1',
    name: 'TOZ-106',
    repair: 'A',
    ammo: 'ammo_20x70_buck',
  },
  {
    id: 'wpn_wincheaster1300',
    name: 'TOZ-194',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_toz34',
    name: 'TOZ-34',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_toz34_mark4_23',
    name: 'TOZ-34 "Chimera Hunter"',
    repair: 'B',
    ammo: 'ammo_23x75_shrapnel;ammo_23x75_barrikada',
  },
  {
    id: 'wpn_toz34_obrez',
    name: 'TOZ-34 (Sawn-off)',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_bm16_full',
    name: 'TOZ-66',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
  {
    id: 'wpn_bm16',
    name: 'TOZ-66 (Sawn-off)',
    repair: 'B',
    ammo: 'ammo_12x70_buck;ammo_12x76_zhekan',
  },
];
